Add support for multimedia oasis-tcs/dita#351
dita-ot/dita-ot pull request #3652
Opened 2020-12-17 23:55 UTC by robander

Signed-off-by: Robert D Anderson <gorodki@gmail.com>

---
name: Pull request
about: Propose changes to fix an issue or implement a new feature

---

## Description

Adds basic support for oasis-tcs/dita#351 the new `<audio>` and `<video>` elements. Markup is already supported, this creates the expected HTML5 content. PDF already (correctly) uses the fallback element content, and does not generate an error.

* `href` is rewritten to `src`
* `format` is rewritten to `type` (DITA 2.0 spec clarifies that a MIME type is acceptable in `@format`)
* media attributes are either copied as-is or (for boolean) added if true

## Motivation and Context

These elements were redesigned over the last few months to become base DITA elements in DITA 2.0, which maps closely to HTML5 structure. Without this PR, they generate a bunch of "unknown element" warnings in HTML5.

This basically just maps the DITA markup to the HTML5 markup for `<audio>`, `<video>`, `<source>`, and `<track>`.

The DITA order does not match HTML5, so it explicitly processes source, then track, then any fallback content.

## How Has This Been Tested?

Attaching test case here with the simple case (only href + format) and the complex case (all the multimedia attributes, plus source and track info). Tested HTML is as expected. The attached audio/video files are fake content (copy of a DITA file).
[media.zip](https://github.com/dita-ot/dita-ot/files/5712760/media.zip)

2020-12-18 06:07 UTC, jelovirt requested changes

2020-12-18 06:07 UTC, jelovirt commented on src/main/plugins/org.dita.html5/xsl/topic.xsl
> +        *[not(contains(@class,' topic/media-source') or contains(@class,' topic/media-track'))]"/>
```suggestion
        * except *[contains(@class, ' topic/media-source') or contains(@class, ' topic/media-track')]"/>
```

2020-12-18 06:07 UTC, jelovirt commented on src/main/plugins/org.dita.html5/xsl/topic.xsl
> +        *[not(contains(@class,' topic/media-source') or contains(@class,' topic/media-track'))]"/>
```suggestion
        * except *[contains(@class,' topic/media-source') or contains(@class,' topic/media-track')]"/>
```

2020-12-18 14:17 UTC, jelovirt approved these changes

2020-12-18 22:37 UTC, merged

2022-03-03 14:36 UTC, raducoravu commented
How about support to automatically copy audio and video files to the output folder? Also the [gen-list] stage right now attempts to parse the mp4 file as DITA XML.