Grammar caching and validation for RNG-based topics
dita-ot/dita-ot pull request #3926
Opened 2022-05-13 07:08 UTC by raducoravu

FIxes for #3661 and #3253
Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

## Description
Added grammar caching for Relax NG based DITA topics and maps. Makes publishing faster for such RNG-based DITA projects.
Added validation for Relax NG based DITA topics and maps. Reports in the console validation errors if the topics are invalid according to the RNG schema.

## Motivation and Context
FIxes for #3661 and #3253

## How Has This Been Tested?
Tested manually with a small RNG-based DITA project on Mac OS.

## Type of Changes
Speed performance improvement and removed limitation which did not present validation errors for RNG-based topics.
- New feature _(non-breaking change which adds functionality)_

## Documentation and Compatibility
Maybe mention in the release notes:
Added grammar caching for Relax NG based DITA topics and maps. Makes publishing faster for such RNG-based DITA projects.
Added validation for Relax NG based DITA topics and maps. Reports in the console validation errors if the topics are invalid according to the RNG schema.

- What documentation changes are needed for this feature?
Not sure if the limitation that RNG-based publishing did not validate was mentioned anywhere in the user's guide.
- Will this change affect backwards compatibility or other users' overrides?
No

## Checklist
- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

2022-05-13 07:21 UTC, jelovirt requested changes
Are there any unit tests that test that this code is run?

2022-05-13 07:21 UTC, jelovirt commented on src/main/java/org/ditang/relaxng/defaults/RelaxDefaultsParserConfiguration.java
> +	public void setProperty(String propertyId, Object value) throws XMLConfigurationException {
The indentation in this PR uses both 2 and 4 spaces. Could you use 4 spaces for all indents?

2022-05-13 07:21 UTC, jelovirt commented on src/main/java/org/ditang/relaxng/defaults/RelaxNGDefaultValues.java
> +      List<Attribute> list = defaults.get(key);
Doesn't this change just change the code from `computeIfAbsent` to doing the exact same thing "manually"?

2022-05-13 07:21 UTC, jelovirt commented on src/main/java/org/ditang/relaxng/defaults/pool/RNGDefaultsEnabledGrammarPool.java
> + * Copyright 2011 George Bina
Shouldn't this be 
```suggestion
 * Copyright 2022 Radu Coravu
```

2022-05-13 07:21 UTC, jelovirt commented on src/main/java/org/ditang/relaxng/defaults/pool/RNGDefaultsEnabledSynchronizedXMLGrammarPoolImpl.java
> + */
Wrong copyright or if this needs to be retained, then this PR cannot be merged.

2022-05-13 07:21 UTC, jelovirt commented on src/main/java/org/ditang/relaxng/defaults/pool/RNGDefaultsEnabledSynchronizedXMLGrammarPoolImpl.java
> +   * @see ro.sync.xml.parser.RNGDefaultsEnabledGrammarPool#getRngDefaultValues(java.lang.String)
```suggestion
   * @see org.ditang.relaxng.defaults.pool.RNGDefaultsEnabledGrammarPool#getRngDefaultValues(java.lang.String)
```

2022-05-13 07:21 UTC, jelovirt commented on src/main/java/org/ditang/relaxng/defaults/pool/RNGDefaultsEnabledSynchronizedXMLGrammarPoolImpl.java
> +   * @see ro.sync.xml.parser.RNGDefaultsEnabledGrammarPool#putRngDefaultValues(java.lang.String, org.ditang.relaxng.defaults.RelaxNGDefaultValues)
```suggestion
   * @see org.ditang.relaxng.defaults.pool.RNGDefaultsEnabledGrammarPool#putRngDefaultValues(java.lang.String, org.ditang.relaxng.defaults.RelaxNGDefaultValues)
```

2022-05-13 07:24 UTC, jelovirt requested changes

2022-05-13 07:24 UTC, jelovirt commented on src/main/java/org/ditang/relaxng/defaults/RelaxNGDefaultValues.java
> +      }
Doesn't this change just change the code from `computeIfAbsent` to doing the exact same thing "manually"?

2022-05-13 13:33 UTC, chrispy-snps commented
@raducoravu - thank you for contributing this!

The runtime improvement is significant:

```
$ time ~/git/dita-ot/src/main/bin/dita -i dita/ptug.ditamap -f html5 -o out1
real    4m30.200s
user    3m46.234s
sys     1m41.484s
$ time ~/git/dita-ot-cached/src/main/bin/dita -i dita/ptug.ditamap -f html5 -o out2
real    0m59.383s
user    1m18.000s
sys     0m32.313s
```

The baseline and RelaxNG-cached output directories are identical.

I confirmed that both DTD and RelaxNG topics now show similar-but-different validation messages:

```
 [gen-list] [DOTJ013E][ERROR] Failed to parse the referenced file 'file:.../topics/introduction-dtd.dita'.: file:.../topics/introduction-dtd.dita Line 10:The content of element type "topic" must match "(title,titlealts?,(shortdesc|abstract)?,prolog?,body?,related-links?,topic*)".

 [gen-list] [DOTJ013E][ERROR] Failed to parse the referenced file 'file:.../topics/introduction-rng.dita'.: file:.../topics/introduction-rng.dita Line 4:element "prolog" not allowed yet; missing required element "title"
```

The transformation behavior was consistent between DTD and RelaxNG in that the invalid topic was excluded from both final transformation results.

2022-05-16 03:44 UTC, raducoravu commented
@chrispy-snps thanks for the tests, out of curiosity can you also post the times you get using the DITA OT bundled with Oxygen 24.1? It should have the fix included but I discovered that the fix may not have fully worked with it.

2022-05-16 07:28 UTC, raducoravu commented
I added 2 auto tests to check that the grammar pool is used (but contains only unique schemas):
org.dita.dost.IntegrationTest.testRngGrammarPool()
org.dita.dost.IntegrationTest.testRngNoGrammarPool()

And 2 auto tests that the validate parameter is used:
org.dita.dost.IntegrationTestPreprocess1.testRngGrammarPoolValidate()
org.dita.dost.IntegrationTestPreprocess1.testRngGrammarPoolNoValidate()

I cannot add this latter tests to the common IntegrationTest because of this existing issue with preprocess2:
https://github.com/dita-ot/dita-ot/issues/3281
"preprocess2" does not break the parsing of an XML resource if the error handler returns exceptions for it. "preprocess" works correctly.

2022-05-16 14:55 UTC, chrispy-snps commented
@raducoravu - The previous testcase did not show much difference, 59s for the cached DITA-OT versus 62s for the Oxygen Publishing Engine 2022041502.

I tried a different testcase with more (2300) smaller files. The results are as follows, averaged across several runs and with validation disabled for consistency:

* 262s for DITA-OT, cached
* 310s for Oxygen Publishing Engine 2022041502
* 971s for DITA-OT 3.7.2

2022-06-03 08:53 UTC, jelovirt approved these changes

2022-06-03 08:54 UTC, merged

2022-06-03 09:27 UTC, raducoravu commented
Thanks @jelovirt