Fix for #3353, properly detect image format on keydef to image.
dita-ot/dita-ot pull request #3963
Opened 2022-07-05 09:28 UTC by raducoravu

Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

## Description
Properly determine that a keydef to an image has image format.

## Motivation and Context
Fixes #3353

## How Has This Been Tested?
Automatic test.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
No doc.

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

2022-08-01 09:05 UTC, jelovirt requested changes

2022-08-01 09:05 UTC, jelovirt commented on src/main/java/org/dita/dost/reader/GenListModuleReader.java
> +            if(format != null && org.dita.dost.util.FileUtils.isSupportedImageFile("." + format)) {
Use static import for `isSupportedImageFile` and use space after `if`.

2022-08-01 12:07 UTC, raducoravu commented
@jelovirt I think I managed to mess this up, I did a fetch upsteam on Github and I think I broke this pull request which now has too many commits. Should I close it and open a new one? I do not think I have the knowledge to fix it in other ways.

2022-08-02 04:20 UTC, raducoravu commented
@jelovirt I think I managed to revert the merge update I made by mistake on the branch, then performed the code review you mentioned.

2022-08-02 13:14 UTC, merged