3985  No alternate text specified when reading out loud TOC entries
dita-ot/dita-ot pull request #3986
Opened 2022-08-08 09:19 UTC by jlacour31

Signed-off-by: Julien Lacour <julien@sync.ro>

## Description
Add a fox:alt-text attribute for each TOC entry, this attribute is set with the navtitle.

## Motivation and Context
Fix https://github.com/dita-ot/dita-ot/issues/3985.

## How Has This Been Tested?
Not tested, I don't know if this is possible.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Checklist
- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

2022-08-08 09:20 UTC, jelovirt requested changes
FOP specific features should go to `org.dita.pdf2.fop` plug-in, not the base `org.dita.pdf2` plug-in.

2022-08-18 12:56 UTC, jlacour31 commented
A solution could be to add a new attribute in `org.dita.pdf2/xsl/fo/toc.xsl` and transform it in @fox:alt-text in an `org.dita.pdf2.fop/xsl/fo/toc_fop.xsl` new stylesheet.

2022-08-19 07:42 UTC, jlacour31 commented
A solution could be to call a new template in `org.dita.pdf2\xsl\fo\toc.xsl` and create this template in all three pdf2 plugins (axf, fop, xep) but only implement it in `org.dita.pdf2.fop`.

2022-10-20 14:21 UTC, jelovirt approved these changes

2022-10-20 14:21 UTC, merged