Fix `args.xhtml.toc.class` and `args.html5.toc.class`
dita-ot/dita-ot pull request #4065
Opened 2022-11-25 13:40 UTC by chrispy-snps

## Description
This pull request re-implements the `args.xhtml.toc.class` and `args.html5.toc.class` parameters, which were documented but somehow became omitted from the processing pipeline.

## Motivation and Context
Fixes #4015.

## How Has This Been Tested?
I tested all four combinations of defining `@outputclass` on the `<map>` and setting the DITA-OT parameter, for both the `xhtml` and `html5` transformation types.

I ran `gradlew test` and `gradle e2etest`.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

The DITA-OT `args.xhtml.toc.class` and `args.html5.toc.class` parameters are converted to `$OUTPUTCLASS` stylesheet parameters. This fix updates the `@outputclass` attribute creation for TOC page `<body>` elements to also consider `$OUTPUTCLASS`.

## Documentation and Compatibility
A release notes mention is sufficient.

This change should not adversely affect any existing plugins or flows.

## Checklist
- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>

2022-11-25 13:47 UTC, chrispy-snps commented
@jelovirt - what is a good way to add test coverage for `args.xhtml.toc.class` and `args.html5.toc.class`? I read through #4009 and I thought maybe I could modify one of the end-to-end tests to set this parameter and change the expected output accordingly. What do you think?

2022-12-02 13:26 UTC, chrispy-snps commented
To make the intent clearer, I changed

`<xsl:if test="@outputclass[. ne ''] or $OUTPUTCLASS[. ne '']">`

to

`<xsl:if test="(@outputclass ne '') or ($OUTPUTCLASS ne '')">`

Functionality is identical, all tests pass.

2022-12-02 16:57 UTC, robander approved these changes

2022-12-03 09:09 UTC, jelovirt requested changes
Handle all whitespace values

2022-12-03 09:09 UTC, jelovirt commented on src/main/plugins/org.dita.html5/xsl/cover.xsl
> +      <xsl:if test="(@outputclass ne '') or ($OUTPUTCLASS ne '')">
```suggestion
      <xsl:if test="normalize-space(@outputclass) or normalize-space($OUTPUTCLASS)">
```

2022-12-03 09:09 UTC, jelovirt commented on src/main/plugins/org.dita.xhtml/xsl/map2htmtoc/map2htmlcoverImpl.xsl
> +      <xsl:if test="(@outputclass ne '') or ($OUTPUTCLASS ne '')">
```suggestion
      <xsl:if test="normalize-space(@outputclass) or normalize-space($OUTPUTCLASS)">
```

2022-12-03 09:16 UTC, jelovirt commented on src/main/plugins/org.dita.html5/xsl/cover.xsl
> +        <xsl:attribute name="class" select="string-join(distinct-values((tokenize(@outputclass, '\s+'), tokenize($OUTPUTCLASS, '\s+'))), ' ')"/>
If the values have leading whitespace, this will result in leading whitespace for the resulting `@class` attribute, but IMO it's ok to just leave it.

2022-12-03 09:19 UTC, jelovirt approved these changes

2022-12-03 10:44 UTC, merged

2022-12-03 12:11 UTC, chrispy-snps commented
Thanks @jelovirt, that is a more elegant test! I appreciate the improvement and noted the technique.