Resolve <longdescref> @keyref references to @href
dita-ot/dita-ot pull request #4080
Opened 2022-12-10 16:21 UTC by chrispy-snps

Signed-off-by: chrispy <chrispy@synopsys.com>

## Description
Adds `<longdescref>` element to the list of elements considered for `@keyref` resolution.

Thanks to @raducoravu for identifying the fix!

## Motivation and Context
Fixes #4071.

## How Has This Been Tested?
I ran the testcase from #4071 and confirmed that `@keyref` is now resolved to `@href`:

```
$ diff temp-orig-06-keyref/topic.dita temp-fixed-06-keyref/topic.dita
55c55
<          <longdescref keyref="topic"/>
---
>          <longdescref keyref="topic" href="topic.dita"/>
```

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
A release notes mention should be sufficient.

## Checklist
- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>

I did not update any tests for this fix, as the code change is simple and I would not expect future code updates to break the fix for this specific element.

2022-12-12 20:01 UTC, robander approved these changes

2022-12-16 06:46 UTC, jelovirt commented
We should cherry-pick this into `hotfix4.0.2`

2022-12-16 08:14 UTC, jelovirt commented
@chrispy-snps could you create a branch with this same name off `hotfix/4.0.2` and cherry-pick the commit from the branch to that branch. Then force push the new branch to remote onto the old branch? This will replace the old one and change the PR to target to `hotfix/4.0.2`.

2022-12-16 08:14 UTC, jelovirt requested changes
Needs to change the target branch to `hotfix/4.0.2`

2022-12-18 15:52 UTC, chrispy-snps commented
I rebased just this PR's single commit, using the following command:

`git rebase --onto hotfix/4.0.2 fix/4071~1 fix/4071`

2022-12-20 13:58 UTC, jelovirt approved these changes

2022-12-20 13:58 UTC, merged