Update FOP to 2.9
dita-ot/dita-ot pull request #4288
Opened 2023-10-01 08:06 UTC by jelovirt

## Description
Update FOP and related libraries to version 2.9.

## Motivation and Context
Fixes #4272

## How Has This Been Tested?
Existing tests pass and manual testing.

## Type of Changes
- New feature _(non-breaking change which adds functionality)_

2023-10-03 03:43 UTC, raducoravu requested changes

2023-10-03 03:43 UTC, raducoravu commented on src/main/config/logback.xml
I do not understand what this line is for.
There are still errors like:

     [ERROR] Unsupported TrueType font: No Unicode or Symbol cmap table not present. Aborting

reported in the console when running the DITA OT on my mac. If you want such lines to disappear which makes sense you could maybe turn it off:

     <logger name="org.apache.fop.fonts.truetype.TTFFile" level="OFF"/>

2023-10-03 05:27 UTC, jelovirt commented on src/main/config/logback.xml
@raducoravu if you remove the configuration and run `dita` CLI, you notice what messages the configuration removes. That error should not be ignored.

2023-10-03 05:35 UTC, raducoravu commented on src/main/config/logback.xml
I tried this but I do not notice what messages the configuration removes. There are usually lots of messages when fonts are loaded and cached by Apache FOP on the first run. Once they are cached on subsequent runs I do not have any extra message that the line you added would hide.

2023-10-03 05:35 UTC, raducoravu approved these changes

2023-10-04 14:21 UTC, jelovirt commented on src/main/config/logback.xml
I can't reproduce the log messages now because I don't remember how I got them.

2023-10-04 14:22 UTC, merged