use `@class="compact"` instead of `@compact="yes"` for HTML outputs
dita-ot/dita-ot pull request #4303
Opened 2023-10-14 17:51 UTC by chrispy-snps

## Description
Use `@class="... compact"`  instead of `@compact="yes"` for the XHTML and HTML5 outputs. The relevant CSS rules are updated accordingly.

Although the deprecation applies only to HTML5, the XHTML transformation was also updated for consistency.

## Motivation and Context
Fixes #4298.

## How Has This Been Tested?
I ran the testcase in #4298 for both XHTML and HTML5 and confirmed that the browser results were visually identical. I also ran `./gradlew check`.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
No documentation change is needed for this fix.

A release notes entry could be something like:

> The DITA standard defines a `@compact` attribute for list elements. Previously, this attribute was published to XHTML and HTML5 outputs as a `@compact` attribute. However, the `@compact` attribute was deprecated in HTML4 (over 20 years ago). Now, DITA `@compact` attributes are published as `@class="compact"` keywords in both the XHTML and HTML5 outputs. The default CSS rules have been updated accordingly. Custom CSS rules referencing the `@compact` attribute should be updated.

## Checklist
- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>

2023-10-21 15:52 UTC, chrispy-snps commented
XHTML output:
```diff
39c39
<         <ol class="ol" compact="compact">
---
>         <ol class="ol compact">
66c66
<         <ul class="ul" compact="compact">
---
>         <ul class="ul compact">
93c93
<         <ul class="sl simple" compact="compact">
---
>         <ul class="sl simple compact">
144c144
<         <dl class="dl" compact="compact">
---
>         <dl class="dl compact">
```

HTML5 output:
```diff
16c16
<         <ol class="ol" compact>
---
>         <ol class="ol compact">
31c31
<         <ul class="ul" compact>
---
>         <ul class="ul compact">
46c46
<         <ul class="sl simple" compact>
---
>         <ul class="sl simple compact">
79c79
<         <dl class="dl" compact>
---
>         <dl class="dl compact">
```

2023-12-20 16:18 UTC, infotexture requested changes
See suggestions on preserving attribute selectors for backwards compatibility.

2023-12-20 16:18 UTC, infotexture commented on src/main/plugins/org.dita.html5/sass/_lists.scss
> +.compact > li {
For backwards compatibility, let's preserve the attribute selector to ensure the rule continues to work on any files generated by previous toolkit versions:


```suggestion
*[compact="yes"] > li,
.compact > li {
```

2023-12-20 16:18 UTC, infotexture commented on src/main/plugins/org.dita.html5/sass/_lists.scss
```suggestion

/* Compact lists use attributes up to DITA-OT 4.1.2, classes thereafter */
```

2023-12-20 16:18 UTC, infotexture commented on src/main/plugins/org.dita.html5/sass/_lists.scss
> -
Let's preserve this rule too

2023-12-21 00:14 UTC, chrispy-snps commented
@infotexture - good suggestion! I updated the CSS to be backward compatible with HTML generated in previous releases. The changes assume that this merge request will be implemented in DITA-OT 4.1.3.

2023-12-22 16:14 UTC, infotexture approved these changes
My impulse was to re-use the existing rule and just add the new class selector, but a separate rule may be more readable. 👍 

> The changes assume that this merge request will be implemented in DITA-OT 4.1.3.

We'll need to confirm that and update the comments accordingly if not.

2023-12-22 17:53 UTC, chrispy-snps commented
> My impulse was to re-use the existing rule and just add the new class selector, but a separate rule may be more readable. 👍

I was also going to keep them combined, but then I realized that keeping them separate would help future-us delete the obsoleted rules after we've forgotten all the details!

2023-12-28 08:39 UTC, jelovirt approved these changes

2023-12-28 08:40 UTC, merged

2023-12-29 14:59 UTC, infotexture commented
@jelovirt This was merged to `develop` but code comments mention 4.1.3, so we'll need to [remember](https://github.com/dita-ot/dita-ot/pull/4303#pullrequestreview-1794690602) to either cherry pick if a corresponding hotfix is released, or update those to reflect the released version that actually includes the changes.