Draft: In `index.html` metadata, ignore <keyword> metadata in `@keys` definitions
dita-ot/dita-ot pull request #4410
Opened 2024-02-17 12:41 UTC by chrispy-snps

## Description
Updates the HTML5 metadata generation in `index.html` to *not* consider `<keyword>` elements in variable definitions.

## Motivation and Context
Fixes #4405.

## How Has This Been Tested?
I ran the testcase from #4405. I also ran the usual tests.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

In `get-meta.xsl`, the metadata template that matches `<keywords>` elements is updated to exclude any elements that have a `@keys` attribute in the element ancestry.

## Documentation and Compatibility
No documentation change is needed. A release notes entry could be as follows:

> In the DITA-OT 4.2 release, the HTML5 transformation was updated to include map-level `<keywords>` metadata in the `index.html` file (#4351, #4352). However, this inadvertently also included variable definition keywords. In this release, only `<keywords>` not a part of any `@keys` definition are considered. (#4405)

## Checklist
- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>

2024-02-17 12:47 UTC, jelovirt requested changes

2024-02-17 12:50 UTC, jelovirt commented
@chrispy-snps if you have a draft PR, based on the title prefix "Draft: ", it's better to use a draft PR.

2024-02-17 13:12 UTC, jelovirt requested changes

2024-02-17 13:12 UTC, jelovirt commented on src/main/plugins/org.dita.html5/xsl/get-meta.xsl
> +                            descendant::*[contains(@class,' map/topicmeta ')][not(ancestor::*[@keys])]/*[contains(@class,' topic/keywords ')]/descendant-or-self::* |
Actually, why does this start with `descendant` axis? That's the problem, it seems. Remove that and replace something that doesn't use any depth, that's the correct fix. Same applies to `prolog` for topics, it's using `descendant` without any reason.

2024-02-17 14:03 UTC, chrispy-snps commented on src/main/plugins/org.dita.html5/xsl/get-meta.xsl
> +                            descendant::*[contains(@class,' map/topicmeta ')][not(ancestor::*[@keys])]/*[contains(@class,' topic/keywords ')]/descendant-or-self::* |
I think the `descendant` axis for `prolog` is for nested topics:

```
<topic id="topic">
  <title>Topic</title>
  <prolog>...</prolog>
  ...
  <topic id="subtopic">
    <title>Subtopic</title>
    <prolog>...</prolog>
  </topic>

</topic>
```

In our content, we use nested topics/prologs for `<author>` metadata and context-sensitive help `<resourceid>` labels.

2024-02-17 14:08 UTC, chrispy-snps commented
@jelovirt - thanks for the note on correctly filing draft PRs!

I filed this as Draft because I was going to ask the senior developers for feedback on the correct exclusion filter. But while writing up my thoughts in that message, I led myself to a conclusion.

Originally I was going to remove the `descendant` axis as you mentioned. But I think exclusions are better done by semantics than structure. For example, map-level metadata might be organized into `topicgroup` containers (we do this in some more complex publications), or perhaps a future version of the DITA (or user plugins similar to what @kirkilj uses) might explicitly populate keywords in `<submap>` containers for downstream processing.

After thought and experimentation, I updated this PR to exclude both `@keys`-related and `@href`-related `<keyword>` elements. Given the following DITA map:

```
<map>
  <title>My Map</title>

  <!-- keyword metadata -->
  <topicmeta>
    <keywords>
      <keyword>keyword1</keyword>
    </keywords>
  </topicmeta>

  <!-- keyword metadata in topicgroup-->
  <topicgroup>
    <topicmeta>
      <keywords>
        <keyword>keyword2</keyword>
      </keywords>
    </topicmeta>
  </topicgroup>

  <!-- variable definition -->
  <keydef keys="var1">
    <topicmeta>
      <keywords>
        <keyword>variable1</keyword>
      </keywords>
    </topicmeta>
  </keydef>

  <!-- keyword metadata in a non-@keys topicref -->
  <topicref href="topic.dita">
    <topicmeta>
      <keywords>
        <keyword>keyword-in-nonkeys-topicref</keyword>
      </keywords>
    </topicmeta>
  </topicref>

  <!-- keyword metadata in a @keys topicref -->
  <topicref href="topic.dita">
    <topicmeta>
      <keywords>
        <keyword>keyword-in-keys-topicref</keyword>
      </keywords>
    </topicmeta>
  </topicref>

</map>
```

the `index.html` metadata is as follows:

```
<meta name="keywords" content="keyword1, keyword2">
```

which is what I would expect for truly map-level metadata.

Feedback is welcomed!

2024-02-22 11:32 UTC, chrispy-snps commented
If there's no further feedback or dissent, I think this should be included in 4.2.1.

2024-02-23 12:46 UTC, jelovirt commented
In the example, I don't think `keyword2` should be included in the keywords list. It's inside a `<topicgroup>`, not part of the root metadata. @robander what's your take?

2024-02-24 08:56 UTC, jelovirt commented
Opened https://github.com/dita-ot/dita-ot/pull/4418 as I think this fix is incorrect. Nested topicmeta should not be used for `index.html`. For example if you have 2000 topicrefs and each has a two keywords in the topicmeta, the `index.html` would have 10 000 keywords in the HTML metadata. It can be argued that `index.html` "contains" all the content in the source set, but IMO `index.html` is the TOC, not "everything in the source set". If you replace keyword with author metadata, IMO it's not intuitive to think that `index.html` has been written by 10 000 different author just because each topic has two distinct authors.

2024-02-24 10:27 UTC, chrispy-snps commented
@jelovirt - my fix does not collect from topic references, as explained in my description and shown in my example. I would have preferred an opportunity to receive feedback and refine the fix, if needed.

2024-02-24 13:51 UTC, chrispy-snps commented
@robander - Thanks for your detailed thoughts.

For topics, I agree that **nested-subtopic prologs should be considered**. We use nested subtopics with topic/subtopic prologs regularly. All are relevant to the document as a whole.

For maps, we sometimes use bare `<topicgroup>` as containers to organize things in the Oxygen DITA Maps Manager tree view. So my mental model is that they are intrinsically transparent unless decorated with attributes that require otherwise. I tried to to be semantic in my solution, but perhaps it is better to take a more conservative approach and expand as needed.

But the root-map metadata we *need* for our flow is at the `<map>` root. Plus, #4418 has unit tests, which is always good. So I'm closing this request in favor of that one.

2024-02-24 13:51 UTC, closed without merging